server:
  port: 8080
mybatis:
  configLocation: classpath:mybatis/mybatis-config.xml
  mapperLocations: classpath*:mybatis/**/*Mapper.xml
  typeAliasesPackage: lyh.demo.shardingtest.domain
spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:config.yaml
